Add a test for Utils.buildImageDataUrl().
        * src/test/java/org/glom/web/server/UtilsTest.java:
Add this tests because this method has started failing with this
exception, and maybe this will help to debug it:
java.lang.NoSuchMethodError: org.apache.http.client.utils.URLEncodedUtils.encPath(Ljava/lang/String;Ljava/nio/charset/Charset;)Ljava/lang/String;